### ISSUE TITLE
Assertion `op_mapping.find(name_str) != op_mapping.end()' failed

### ISSUE THREAD

**Issue by AstroCIEL** [pku-liang/hlcd-hls-lab-handout#3]
![image](https://github.com/user-attachments/assets/5be26d90-1337-427c-aec2-35ac8e065670)
请问这个报错是哪里出现了问题呢

**Comment by Henry-Jessie** [comment]
看下schedule.txt文件是否有对应的周期调度

**Comment by Henry-Jessie** [comment]
看下test文件夹中的ir和op是否完整。而且执行test的命令格式是make test TEST=1
