### ISSUE TITLE
关于minisat的安装问题

### ISSUE THREAD

**Issue by atarchive** [pku-liang/hlcd-hls-lab-handout#4]
貌似我直接使用git submodule init -- minisat并不能将相应的子模块clone下来，我使用了：
git clone https://github.com/niklasso/minisat.git
cd minisat
git checkout 37dc6c67e2af26379d88ce349eb9c4c6160e8543
之后再运行所给代码make即可

**Comment by Henry-Jessie** [comment]
原来的readme少了一个git submodule update命令。
也可以通过直接运行git submodule update --init --recursive来同时初始化和下载子模块，readme已经更新成这一条命令。
同时.gitmodules文件的url已经从git更新为https的格式，如果想按照readme的流程走需要更新一下该url。
